### ISSUE TITLE
Rollback page "Missing Content"

### ISSUE THREAD

**Issue by steakknife** [capistrano/documentation#124]
http://capistranorb.com/documentation/getting-started/rollbacks/

**Comment by leehambley** [comment]
We know @steakknife it's a great opportunity to contribute if you have some hard-won experience with that feature!

**Comment by steakknife** [comment]
Zero.  Was looking for it.

**Comment by mib32** [comment]
@steakknife himself already wrote 50k lines to that repo man :+1:

**Comment by steakknife** [comment]
@mib32 That's great, but it has no pertinence to this issue.  Perhaps you would like to volunteer since you don't have any commits here yet?

**Comment by yb66** [comment]
Documentation is just as important as lines of code, and this is a case in point, and also an example of programmers favouring one over the other (50,000 lines of code yet can't write one on rollbacks? _Really?_)

If no one's going to write anything about it they should at least remove the page.

**Comment by leehambley** [comment]
> If no one's going to write anything about it they should at least remove the page.

Please, feel free to make a contribution.

**Comment by yb66** [comment]
I would've if I'd used that feature, but I was also hoping to read the documentation for it first. Since there are obviously many contributors to both the app and the documentation repos, one of them can do it.

Or I can just make it up if that suits everyone better, and they can keep pumping out the code ;)

**Comment by mattbrictson** [comment]
FWIW, there is already some information relating to rollbacks on the flow page:

http://capistranorb.com/documentation/getting-started/flow/

That could be a starting point for building out better rollback documentation.

**Comment by will-in-wi** [comment]
Thanks for the pointer to the flow docs. I've created a rough draft here: https://github.com/capistrano/documentation/pull/148

If anyone could look over this and make comments, I'd appreciate it!

Thanks!

**Comment by will-in-wi** [comment]
This should be fixed now.
