### ISSUE TITLE
Doc site is down

### ISSUE THREAD

**Issue by blainsmith** [capistrano/documentation#132]
http://capistranorb.com is throwing a GitHub Pages 404.

**Comment by leehambley** [comment]
I renamed the repository an hour or so ago, since then the GH pages has been down. Still investigating why.

**Comment by leehambley** [comment]
Reported to GH as I have exhausted everything I can think of to fix it.

**Comment by leehambley** [comment]
(I renamed it back minutes later, after noticing that the site was broken)

**Comment by baweaver** [comment]
Is there any way to ensure there's a backup in case something like this is to happen again? With such a critical piece of infrastructure for some companies, this can be a major setback.

**Comment by louim** [comment]
@baweaver imho, since the git repo is still up, the informations, even if it's not the best format, is still accessible. You could alway compile and run the site locallly :smile:

**Comment by blainsmith** [comment]
@leehambley I wonder if changing CNAME to something else, committing, changing it back, recommitting again would rekick the GitHub cache of their domain mapping. Just a thought.

**Comment by mattr-** [comment]
What @blainsmith said. Although I think pushing an empty commit would be cleaner: `git commit --allow-empty -m "force site rebuild"`

**Comment by leehambley** [comment]
Site ought to be rebuilding now.

**Comment by leehambley** [comment]
I tried the suggestions, both ways (see `HEAD^5`), waiting again for GH support.

**Comment by leehambley** [comment]
Fixed https://help.github.com/articles/user-organization-and-project-pages - apparently the naming is significant, and depending on the name the branch name is significant.

**Comment by blainsmith** [comment]
Ahhh yeah. I missed that part. Glad you got it figured out.

**Comment by leehambley** [comment]
Thanks for the patience, kind of embarrassing. Serves me right for trying
to fix it on zero sleep.

**Comment by blainsmith** [comment]
No worries man. It happens. We've all been there haha.
