### ISSUE TITLE
Check for, and correct gender specific language

### ISSUE THREAD

**Issue by leehambley** [capistrano/documentation#53]
http://www.joyent.com/blog/the-power-of-a-pronoun

**Comment by will-in-wi** [comment]
I've grepped the docs for some gendered pronouns and don't see any. I might have easily missed one, but I'd suggest that this ticket be closed and new ones be opened for issues as they arise.

**Comment by will-in-wi** [comment]
If anything, possibly add to the doc readme a style guide with this as a requirement.

**Comment by leehambley** [comment]
No need.

**Comment by leehambley** [comment]
I don't believe that affirmative action over choice of pronouns is within the scope of problems wortt spending time on. The rest of the Ruby, Python and Node.js communities took that discussion a lot further, and awareness was raised. I also note that I've never had a single complaint from anyone, so consider it closed unless we have others with differing opinions around.
