### ISSUE TITLE
Install CodersClan Tag

### ISSUE THREAD

**Issue by leehambley** [capistrano/documentation#74]
We missed this one, somehow. The CodersClan author reached out to me again, and I don't see the harm in trying this.

```
Need help with getting Capistrano up and running? Got a code problem you want to get solved quickly? 

Get <a href="http://codersclan.net/?repo_id=325">Capistrano support on CodersClan.</a>

<a href="http://codersclan.net/?repo_id=325"><img src="http://www.codersclan.net/gs_button/?repo_id=325" width="200"></a>
```

I wonder where we can best place it. At least:

* [x] Capistrano README
* [ ] Capistrano CONTRIBUTING
* [ ] On the documentation site somewhere.

**Comment by will-in-wi** [comment]
It looks like this is fixed. https://github.com/capistrano/capistrano/pull/893
