### ISSUE TITLE
External deploy.rb (-f flag?) Usage / Error

### ISSUE THREAD

**Issue by brandonrich** [capistrano/documentation#78]
I'm trying to maintain my deploy.rb separately from the (multiple) apps that use it.  I was told that the -f (--rakefile) flag would let me do this, but I'm getting an error and I can't find enough information on this feature to know if I'm using it correctly.  What's the best way to accomplish my goal here?

This deploy.rb has a simple task that does this:
p "hello"
It works in config/deploy.rb, but if I try to reference it from another path...

/my_app_home> bundle exec cap vagrant --rakefile /home/vagrant/cap-external/deploy.rb test:echo

cap aborted!
undefined local variable or method `tasks_without_stage_dependency' for #<Capistrano::Application:0x00000002aad8e8>
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/capistrano-3.1.0/lib/capistrano/application.rb:28:in `top_level_tasks'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/capistrano-3.1.0/lib/capistrano/application.rb:15:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/capistrano-3.1.0/bin/cap:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p353/bin/cap:23:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p353/bin/cap:23:in `<main>'
/usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/capistrano-3.1.0/lib/capistrano/application.rb:36:in `exit_because_of_exception': undefined method `deploying?' for #<Capistrano::Application:0x00000002aad8e8> (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/rake-10.1.1/lib/rake/application.rb:175:in `rescue in standard_exception_handling'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/capistrano-3.1.0/lib/capistrano/application.rb:15:in `run'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/capistrano-3.1.0/bin/cap:3:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/bin/cap:23:in `load'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/bin/cap:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'

**Comment by Kriechi** [comment]
@brandonrich is this still an issue - or can it be closed?

As far as I understand this Capistrano uses the `Capfile` instead of `Rakefile`. So if you only use your `deploy.rb` you are missing all the `require` statements from the `Capfile`...

**Comment by will-in-wi** [comment]
It's been a year since the last comment was made. This can probably be closed.
