### ISSUE TITLE
Leveraging the power of Jekyll/Ruby for more "dynamic" documentation generation

### ISSUE THREAD

**Issue by x3ro** [capistrano/documentation#83]
When I submitted a PR to the Capistrano Docs repo I couldn't help but notice that it'd be nice to have things like `navigation.html` generated automatically. I then started working on doing exactly that, and then noticed that the reason this is not already being done is (probably) that the site is currently being built by GitHub pages, and thus does not allow for custom code.

Would it be an option to build the docs page locally and then push the generated site to GitHub Pages (all this using a Rake task of course)? This would make writing/updating docs more pleasant, I think.

**Comment by will-in-wi** [comment]
This is an old ticket. Could a decision be made one way or the other and this turned into a task?

It sounds like the decision was made to do navigation manually.

**Comment by leehambley** [comment]
Close it. we did it already, the current Jekyll based site is younger than this ticket.
