### ISSUE TITLE
Next/Previous page links

### ISSUE THREAD

**Issue by MarkMurphy** [capistrano/documentation#90]
I found it difficult to know where I was in the documentation. After reading a page I had to scroll up to the top of the sidebar navigation and match the anchor text to the slug in the url to figure out what page I was on and what page I needed to navigate to next.

It would be nice to have the side navigation items have an active state as well as links at the bottom of each page. Something like this would be nice:

```html
<a href="...">Previous: Installation</a>
<a href="...">Next: Authentication &amp; Authorization</a>
```

Also, the link text in the repo has "Authentication & Authorisation" which is spelled incorrectly. It should be "Authentication & Authorization"

**Comment by Kriechi** [comment]
Back to the topic: it's pretty hard to add these links - because Github Pages does not allow jekyll plugins. Therefore we would have to do it manually, and thats hard to keep track of in each PR and change. Eventually it will break again and again. But if you can come up with something JS-based, would be interesting...

**Comment by MarkMurphy** [comment]
Bootstrap seems to be doing ok with it and they're also on Github pages

**Comment by Kriechi** [comment]
any link to that? how are they doing it?
I'm not saying it can't be done - but every commit must be checked.
Otherwise it gets messy pretty fast...

**Comment by MarkMurphy** [comment]
> any link to that? how are they doing it?

https://github.com/twbs/bootstrap/tree/master/docs

jekyll layouts and includes

**Comment by will-in-wi** [comment]
I don't see that Bootstrap is still doing this.
